---
title: "Full references"
---

## Expanded reference list

This page contains a library of academic references that helped define this social-ecological monitoring toolkit.

- Astruch, P., Boudouresque, C.-F., Ferrando-Demange, J., Belloni, B., Charbonnel, É., Gravez, V., and Schohn, T. (2026). Passive restoration of a Mediterranean Posidonia oceanica seagrass meadow: A 40-year survey. Marine Environmental Research 217, 107965.
- Barry, S.C., Raskin, K.N., Hazell, J.E., Morera, M.C., and Monaghan, P.F. (2020). Evaluation of interventions focused on reducing propeller scarring by recreational boaters in Florida, USA. Ocean & Coastal Management 186, 105089.
- Bennett, E.M., and Reyers, B. (2024). Disentangling the complexity of human–nature interactions. People and Nature 6, 402-409.
- Boucek, R.E., Anderson, K.A., Jones, B.L., and Rehage, J.S. (2024). When fishers ask for more protection: Co-produced spatial management recommendations to protect seagrass meadows from leisure boating. Marine Policy 167, 106227.
- Chirico, A.A.D., McClanahan, T.R., and Eklof, J.S. (2017). Community- and government-managed marine protected areas increase fish size, biomass and potential value. PLoS One 12, e0182342.
- Chitará-Nhandimo, S., Chissico, A., Mubai, M.E., Cabral, A.D., Guissamulo, A., and Bandeira, S. 2022. Seagrass Invertebrate Fisheries, Their Value Chains and the Role of LMMAs in Sustainability of the Coastal Communities—Case of Southern Mozambique. Diversity [Online], 14.
- Cullen-Unsworth, L.C., Nordlund, L.M., Paddock, J., Baker, S., McKenzie, L.J., and Unsworth, R.K. (2014). Seagrass meadows globally as a coupled social-ecological system: implications for human wellbeing. Marine Pollution Bulletin 83, 387-397.
- Cullis-Suzuki, S., Wyllie-Echeverria, S., Dick, K.A., Sewid-Smith, M.D., Recalma-Clutesi, O.K., and Turner, N.J. (2015). Tending the meadows of the sea: A disturbance experiment based on traditional indigenous harvesting of Zostera marina L. (Zosteraceae) the southern region of Canada’s west coast. Aquatic Botany 127, 26-34.
- de los Santos, C.B., Krause-Jensen, D., Alcoverro, T., Marbà, N., Duarte, C.M., van Katwijk, M.M., Pérez, M., Romero, J., Sánchez-Lizaso, J.L., Roca, G., Jankowska, E., Pérez-Lloréns, J.L., Fournier, J., Montefalcone, M., Pergent, G., Ruiz, J.M., Cabaço, S., Cook, K., Wilkes, R.J., Moy, F.E., Trayter, G.M.-R., Arañó, X.S., de Jong, D.J., Fernández-Torquemada, Y., Auby, I., Vergara, J.J., and Santos, R. (2019). Recent trend reversal for declining European seagrass meadows. Nature Communications 10, 3356.
- Delgado-Serrano, M.d.M., Oteros-Rozas, E., Vanwildemeersch, P., Ortíz-Guerrero, C., London, S., and Escalante, R. (2015). Local perceptions on social-ecological dynamics in Latin America in three community-based natural resource management systems. Ecology and Society 20.
- Duarte, C.M., Apostolaki, E.T., Serrano, O., Steckbauer, A., and Unsworth, R.K.F. (2025). Conserving seagrass ecosystems to meet global biodiversity and climate goals. Nature Reviews Biodiversity 1, 150-165.
- Duffy, J.E., Appeltans, W., Benson, A., Connolly, R.M., de la Torre-Castro, M., Dierssen, H.M., Fortes, M.D., Fourqurean, J.W., Hessing-Lewis, M., Jarvis, J.C., Kenworthy, W.J., Krause, J.R., Lara Lopez, A., Lefcheck, J.S., Lizcano-Sandoval, L., Lonneman, M., McKenzie, L., Muller-Karger, F.E., Nakaoka, M., Nordlund, L.M., Provoost, P., Roelfsema, C.M., and Unsworth, R.K.F. (2026). Measuring and Reporting on Seagrass as an Essential Ocean Variable for Science and Management. BioScience 76, 359-374.
- Eklöf, J.S., Fröcklin, S., Lindvall, A., Stadlinger, N., Kimathi, A., Uku, J.N., and McClanahan, T.R. (2009). How effective are MPAs? Predation control and ‘spill-in effects’ in seagrass–coral reef lagoons under contrasting fishery management. Marine Ecology Progress Series 384, 83-96.
- Evans, A.J., Ford, E., and Cullen-Unsworth, L. (2025). Connecting governance and practice views on the barriers and solutions to scaled seagrass restoration in the UK. Marine Policy 180, 106781.
- Fanoro, T.F., Scarlet, M.P., and Bandeira, S.O. 2023. Intertidal Gleaning Exclusion as a Trigger for Seagrass Species and Fauna Recovery and Passive Seagrass Rehabilitation. Diversity [Online], 15.
- Ferretto, G., Glasby, T.M., Poore, A.G., Callaghan, C.T., Housefield, G.P., Langley, M., Sinclair, E.A., Statton, J., Kendrick, G.A., and Vergés, A. (2021). Naturally-detached fragments of the endangered seagrass Posidonia australis collected by citizen scientists can be used to successfully restore fragmented meadows. Biological Conservation 262, 109308.
- Gagnon, K., Bocoum, E.H., Chen, C.Y., Baden, S.P., Moksnes, P.O., and Infantes, E. (2023). Rapid faunal colonization and recovery of biodiversity and functional diversity following eelgrass restoration. Restoration Ecology 31, e13887.
- Gonzalez, A., Vihervaara, P., Balvanera, P., Bates, A.E., Bayraktarov, E., Bellingham, P.J., Bruder, A., Campbell, J., Catchen, M.D., and Cavender-Bares, J. (2023). A global biodiversity observing system to unite monitoring and guide action. Nature ecology & evolution 7, 1947-1952.
- Gray, D.L., Canessa, R.R., Rollins, R.B., Dearden, P., and Keller, C.P. (2010). Understanding recreational boater attitudes to zoning in a proposed marine protected area. Coastal Management 38, 575-597.
- Griffiths, L.L., Connolly, R.M., and Brown, C.J. (2020). Critical gaps in seagrass protection reveal the need to address multiple pressures and cumulative impacts. Ocean & Coastal Management 183, 104946.
- Grimm, K.E., Archibald, J.L., Bonilla-Anariba, S.E., Bood, N., and Canty, S.W. (2023). Framework for fostering just and equitable seagrass policy, management, and social-ecological outcomes: Lessons learned from Belizean marine resource managers. Marine Policy 152, 105606.
- Gurney, G.G., Darling, E.S., Jupiter, S.D., Mangubhai, S., McClanahan, T.R., Lestari, P., Pardede, S., Campbell, S.J., Fox, M., Naisilisili, W., Muthiga, N.A., D’agata, S., Holmes, K.E., and Rossi, N.A. (2019). Implementing a social-ecological systems framework for conservation monitoring: lessons from a multi-country coral reef program. Biological Conservation 240, 108298.
- Helmstedt, K.J., Holden, M.H., Baker, C.M., Elliot-Kerr, S., Greiner, A., Hudgins, E.J., Shea, K., Tulloch, A.I.T., Young, A.R., Zhang, L., and Possingham, H.P. (2025). How monitoring matters for nature conservation: 15 reasons framed in a theory of change. Proceedings of the Royal Society B: Biological Sciences 292, 20252527.
- Hoad, Nicholas M., and Nordlund, Lina M. (2025). Expert Perceptions on Seagrass Governance, Policy and Management in the Western Indian Ocean. Aquatic Conservation: Marine and Freshwater Ecosystems 35, e70223.
- Hope, M., Jones, B.L.H., and Unsworth, R.K.F. (2026). Increasing nutrients negatively impact seagrass-associated biodiversity. Global Ecology and Conservation 67, e04164.
- Isbell, F., Gonzalez, A., Loreau, M., Cowles, J., Díaz, S., Hector, A., Mace, G.M., Wardle, D.A., O'Connor, M.I., and Duffy, J.E. (2017). Linking the influence and dependence of people on biodiversity across scales. Nature 546, 65-72.
- Jänes, H., Carnell, P., Young, M., Ierodiaconou, D., Jenkins, G.P., Hamer, P., Zu Ermgassen, P.S.E., Gair, J.R., and Macreadie, P.I. (2021). Seagrass valuation from fish abundance, biomass and recreational catch. Ecological Indicators 130, 108097.
- Jones, B.L., Nordlund, L.M., Unsworth, R.K.F., Jiddawi, N.S., and Eklöf, J.S. (2021). Seagrass Structural Traits Drive Fish Assemblages in Small-Scale Fisheries. Frontiers in Marine Science 8, 354.
- Jones, B.L., Unsworth, R.K.F., McKenzie, L.J., Yoshida, R.L., and Cullen-Unsworth, L.C. (2018). Crowdsourcing conservation: The role of citizen science in securing a future for seagrass. Mar Pollut Bull 134, 210-215.
- Jones, B.L.H., Coals, L., Cullen-Unsworth, L.C., Lilley, R.J., Bartlett, A., and Unsworth, R.K.F. (2025a). Mapping global threats to seagrass meadows reveals opportunities for conservation. Environmental Research: Ecology 4, 025005.
- Jones, B.L.H., Cullen-Unsworth, L.C., de la Torre-Castro, M., Nordlund, L.M., Unsworth, R.K.F., and Eklöf, J.S. (2022a). Unintended consequences of sustainable development initiatives: risks and opportunities in seagrass social-ecological systems. Ecology and Society 27.
- Jones, B.L.H., Eklöf, J.S., Unsworth, R.K.F., Coals, L., Christianen, M.J.A., Clifton, J., Cullen-Unsworth, L.C., de la Torre-Castro, M., Esteban, N., Huxham, M., Jiddawi, N.S., McKenzie, L.J., Nakaoka, M., Nordlund, L.M., Ooi, J.L.S., and Prathep, A. (2025b). Risks of habitat loss from seaweed cultivation within seagrass. Proceedings of the National Academy of Sciences 122, e2426971122.
- Jones, B.L.H., Santos, R.O., James, W.R., Costa, S.V., Adams, A.J., Boucek, R.E., Coals, L., Cullen-Unsworth, L.C., Shephard, S., and Rehage, J.S. (2024). New directions for Indigenous and local knowledge research and application in fisheries science: Lessons from a systematic review. Fish and Fisheries 25, 647-671.
- Jones, B.L.H., Unsworth, R.K.F., Nordlund, L.M., Ambo-Rappe, R., La Nafie, Y.A., Lopez, M.R., Udagedara, S., and Cullen-Unsworth, L.C. (2022b). Local Ecological Knowledge Reveals Change in Seagrass Social–Ecological Systems. Oceans 3, 419-430.
- Jones, B.L.H., Unsworth, R.K.F., Nordlund, L.M., Eklöf, J.S., Ambo-Rappe, R., Carly, F., Jiddawi, N.S., La Nafie, Y.A., Udagedara, S., and Cullen-Unsworth, L.C. (2022c). Dependence on seagrass fisheries governed by household income and adaptive capacity. Ocean & Coastal Management 225.
- Larrosa, C., Carrasco, L.R., and Milner-Gulland, E.J. (2016). Unintended Feedbacks: Challenges and Opportunities for Improving Conservation Effectiveness. Conservation Letters 9, 316-326.
- Li, J., Huang, Y., Guo, L., Sun, Z., and Jin, Y. (2024). Operationalizing the social-ecological systems framework in a protected area: a case study of Qilian Mountain National Park, Northwestern China. Ecology and Society 29.
- Luff, A.L., Sheehan, E.V., Parry, M., and Higgs, N.D. (2019). A simple mooring modification reduces impacts on seagrass meadows. Scientific Reports 9, 20062.
- McGinnis, M.D., and Ostrom, E. (2014). Social-ecological system framework: initial changes and continuing challenges. Ecology and Society 19, 30.
- McKenzie, L.J., Nordlund, L.M., Jones, B.L., Cullen-Unsworth, L.C., Roelfsema, C., and Unsworth, R.K.F. (2020). The global distribution of seagrass meadows. Environmental Research Letters 15.
- McKenzie, L.J., Yoshida, R.L., Aini, J.W., Andrefouet, S., Colin, P.L., Cullen-Unsworth, L.C., Hughes, A.T., Payri, C.E., Rota, M., Shaw, C., Tsuda, R.T., Vuki, V.C., and Unsworth, R.K.F. (2021). Seagrass ecosystem contributions to people's quality of life in the Pacific Island Countries and Territories. Marine Pollution Bulletin 167, 112307.
- Nair, N.V., Nayak, P.K., Pittman, J., and Frayne, B. (2026). Linking vulnerabilities of small-scale fisheries with seagrass health and water quality. Marine Policy 190, 107145.
- Nordlund, L.M., Unsworth, R.K.F., Gullström, M., and Cullen-Unsworth, L.C. (2018). Global significance of seagrass fishery activity. Fish and Fisheries 19, 399-412.
- Olander, L.P., Johnston, R.J., Tallis, H., Kagan, J., Maguire, L.A., Polasky, S., Urban, D., Boyd, J., Wainger, L., and Palmer, M. (2018). Benefit relevant indicators: Ecosystem services measures that link ecological and social outcomes. Ecological Indicators 85, 1262-1272.
- Ostrom, E. (2009). A general framework for analyzing sustainability of social-ecological systems. Science 325, 419-422.
- Parry-Wilson, H.M., Rees, S.E., Leather, H., Cole, R., Rugg, C., and Attrill, M.J. (2019). Assessing behavioural and social responses to an eco-mooring trial for Zostera marina conservation management in Torbay, Southwest England. Ocean & Coastal Management 180, 104906.
- Partelow, S., and Boda, C. (2015). A modified diagnostic social-ecological system framework for lobster fisheries: Case implementation and sustainability assessment in Southern California. Ocean & Coastal Management 114, 204-217.
- Pergent-Martini, C., Monnier, B., Lehmann, L., Barralon, E., and Pergent, G. (2022). Major regression of Posidonia oceanica meadows in relation with recreational boat anchoring: A case study from Sant'Amanza bay. Journal of Sea Research 188, 102258.
- Pichler, E., Connell, S.D., and McAfee, D. (2025). Improving human well-being through community-led coastal restoration. Biological Conservation 301, 110892.
- Pike, F., Lindström, L., Ekstedt, J., Jiddawi, N.S., and de la Torre-Castro, M. (2024). Dynamic livelihoods, gender and poverty in marine protected areas: Case study from Zanzibar, Tanzania. Ambio 53, 1218-1233.
- Quiros, T.A.L., Croll, D., Tershy, B., Fortes, M.D., and Raimondi, P. (2017). Land use is a better predictor of tropical seagrass condition than marine protection. Biological Conservation 209, 454-463.
- Reyes‐García, V., Fernández‐Llamazares, Á., McElwee, P., Molnár, Z., Öllerer, K., Wilson, S.J., and Brondizio, E.S. (2019). The contributions of Indigenous Peoples and local communities to ecological restoration. Restoration Ecology 27, 3-8.
- Richardson, K., Steffen, W., Lucht, W., Bendtsen, J., Cornell, S.E., Donges, J.F., Drüke, M., Fetzer, I., Bala, G., von Bloh, W., Feulner, G., Fiedler, S., Gerten, D., Gleeson, T., Hofmann, M., Huiskamp, W., Kummu, M., Mohan, C., Nogués-Bravo, D., Petri, S., Porkka, M., Rahmstorf, S., Schaphoff, S., Thonicke, K., Tobian, A., Virkki, V., Wang-Erlandsson, L., Weber, L., and Rockström, J. (2023). Earth beyond six of nine planetary boundaries. Science Advances 9, eadh2458.
- Sagerman, J., Hansen, J.P., and Wikström, S.A. (2020). Effects of boat traffic and mooring infrastructure on aquatic vegetation: A systematic review and meta-analysis. Ambio 49, 517-530.
- Seto, I., Evans, N.T., Carr, J., Frew, K., Rousseau, M., and Schenck, F.R. (2024). Recovery of Eelgrass Zostera marina Following Conversion of Conventional Chain Moorings to Conservation Mooring Systems in Massachusetts: Context-Dependence, Challenges, and Management. Estuaries and Coasts 47, 772-788.
- Solandt, J.-L., Bunce, E., and Parry, M. (2024). Rise Up: Ecological and Social Responses to the Use of Advanced Mooring Systems to Recover Seagrass Habitat at Cawsand, England. Coastal Management 52, 270-288.
- Turschwell, M.P., Connolly, R.M., Dunic, J.C., Sievers, M., Buelow, C.A., Pearson, R.M., Tulloch, V.J.D., Côté, I.M., Unsworth, R.K.F., Collier, C.J., and Brown, C.J. (2021). Anthropogenic pressures and life history predict trajectories of seagrass meadow extent at a global scale. Proceedings of the National Academy of Sciences 118, e2110802118.
- Unsworth, R.K.F., Bertelli, C.M., Coals, L., Cullen-Unsworth, L.C., den Haan, S., Jones, B.L.H., Rees, S.R., Thomsen, E., Wookey, A., and Walter, B. (2023). Bottlenecks to seed-based seagrass restoration reveal opportunities for improvement. Global Ecology and Conservation 48, e02736.
- Unsworth, R.K.F., Cullen-Unsworth, L.C., Jones, B.L.H., and Lilley, R.J. (2022). The planetary role of seagrass conservation. Science 377, 609-613.
- Unsworth, R.K.F., McKenzie, L.J., Collier, C.J., Cullen-Unsworth, L.C., Duarte, C.M., Eklof, J.S., Jarvis, J.C., Jones, B.L., and Nordlund, L.M. (2019). Global challenges for seagrass conservation. Ambio 48, 801-815.
- Unsworth, R.K.F., Sweet, M., Govers, L.L., von der Heyden, S., Vergés, A., Friess, D.A., Jones, B.L.H., Monfared, M.A.A., Steinfurth, R.C., Fariñas-Franco, J.M., Cullen-Unsworth, L.C., Banke, T.L., Tomas, F., Lusk, B.W., Mendzil, A.F., Debney, A.J., Sanderson, W.G., Thomsen, E., Preston, J., Lacey, E.A., Boerder, K., Walton, R., Vadi, T., Brand, J., and Paul, M. (2025). Rethinking marine restoration permitting to urgently advance efforts. Cell Reports Sustainability 2.
- van Katwijk, M.M., Thorhaug, A., Marbà, N., Orth, R.J., Duarte, C.M., Kendrick, G.A., Althuizen, I.H.J., Balestri, E., Bernard, G., Cambridge, M.L., Cunha, A., Durance, C., Giesen, W., Han, Q., Hosokawa, S., Kiswara, W., Komatsu, T., Lardicci, C., Lee, K.-S., Meinesz, A., Nakaoka, M., O'Brien, K.R., Paling, E.I., Pickerell, C., Ransijn, A.M.A., and Verduin, J.J. (2016). Global analysis of seagrass restoration: the importance of large-scale planting. Journal of Applied Ecology 53, 567-578.
- van Katwijk, M.M., Thorhaug, A., Marba, N., Orth, R.J., Duarte, C.M., Kendrick, G.A., Althuizen, I.H.J., Balestri, E., Bernard, G., Cambridge, M.L., Cunha, A., Durance, C., Giesen, W., Han, Q., Hosokawa, S., Kiswara, W., Komatsu, T., Lardicci, C., Lee, K.S., Meinesz, A., Nakaoka, M., O'Brien, K.R., Paling, E.I., Pickerell, C., Ransijn, A.M.A., and Verduin, J.J. (2015). Global analysis of seagrass restoration: the importance of large-scale planting. Journal of Applied Ecology In Press.
- Van Well, L., Isayeva, A., Axel Olsson, P., and Hollander, J. (2023). Public perceptions of cultural ecosystem services provided by beach nourishment and eelgrass restoration in southern Sweden. Nordic Journal of Botany 2023, e03654.
- Vári, Á., Gonzalez, A., and Bennett, E.M. (2025). Monitor social–ecological systems to achieve global goals for biodiversity and nature's contributions to people. BioScience 75, 276-280.
- Xie, Y., Wen, Y., and Cirella, G.T. 2019. Application of Ostrom’s Social-Ecological Systems Framework in Nature Reserves: Hybrid Psycho-Economic Model of Collective Forest Management. Sustainability [Online], 11.
